// apps/src/components/NewBoard.vue
<template>
  <div class="newboard-container">
    <div class="newboard-header">
      <div class="project-name">
        <router-link
          :to="{ name: 'Home' }"
          class="FeedboProject"
        >
          <img
            :src="logoLink"
            alt="Feedbo Logo"
            class="feedbo-main-logo"
          >
          <span class="Feedbo">
            Feedbo
          </span>
        </router-link>
      </div>
      <AccountView class="fb-account-view" />
    </div>
    <div class="content">
      <div class="form-container">
        {{ category.categorys }}
        <h2 class="Create-new-board">
          Create New Board
        </h2>
        <p>Enter your board name. You can change it later.</p>
        <AForm
          id="form"
          :form="form"
          @submit.prevent="handleSubmit()"
        >
          <AFormItem>
            <AInput
              v-decorator="[
                'category',
                {
                  rules: [
                    { required: true, message: 'This is a required field' },
                  ],
                },
              ]"
              placeholder="Enter name project"
              class="input-name-project"
            />
          </AFormItem>
          <AFormItem>
            <AButton
              type="primary"
              html-type="submit"
              class="submit-form-button"
              :loading="category.isLoadingCreateBoard"
            >
              Create <AIcon type="arrow-right" />
            </AButton>
          </AFormItem>
        </AForm>
      </div>
    </div>
  </div>
</template>
<script>
import { mapState } from "vuex";
import AccountView from "@/components/Account/AccountView.vue";
export default {
  components: {
    AccountView,
  },
  data() {
    return {
      form: this.$form.createForm(this, { name: "coordinated" }),
      logoLink:
        window.bigNinjaVoteWpdata.pluginUrl +
        "assets/img/feedbo-logo-square.png",
    };
  },
  methods: {
    handleSubmit() {
      this.form.validateFields((err, values) => {
        if (!err) {
          if (this.user.userAnonymous == true) {
            window.location.href =
              window.bigNinjaVoteWpdata.siteUrl + "/wp-login.php?message=Please sign in to create your own board";
          }
          else {
            const component = this;
            const requestParams = {
              values: values,
              component: component,
            };
            this.$store.dispatch("category/createCategory", requestParams);
          }
        }
      });
    },
  },
  computed: {
    ...mapState([ "category", "user" ]),
  },
  mounted() {
    document.title = window.bigNinjaVoteWpdata.siteName + " | New Board";
    const link =
      document.querySelector("link[rel*='icon']") ||
      document.createElement("link");
    link.type = "image/x-icon";
    link.rel = "shortcut icon";
    link.href =
      window.bigNinjaVoteWpdata.pluginUrl + "assets/img/feedbo-logo-square.png";
    document.getElementsByTagName("head")[0].appendChild(link);
  },
};
</script>

<style scoped lang="scss">
.big-ninja-feedbo {
  div {
    display: block;
  }
  a {
    color: inherit;
    cursor: pointer;
    text-decoration: none;
  }
  .newboard-container {
    background: #27ae60;
    height: 100vh;
  }
  .newboard-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 20px 15px;
  }
  .feedbo-main-logo {
    height: 50px;
    width: 50px;
  }
  .content {
    padding: 30vh 1rem 0px;
    width: 430px;
    margin: auto;
  }
  .FeedboProject {
    display: flex;
    align-items: center;
    font-size: 24px;
    font-weight: bold;
    font-stretch: normal;
    font-style: normal;
    line-height: normal;
    letter-spacing: normal;
    color: #ffffff;
  }
  .Feedbo {
    padding-left: 10px;
  }
  .button {
    width: 230px;
    height: 50px;
    border-radius: 5px;
  }
  .Create-new-board {
    font-size: 21px;
    font-weight: 600;
    color: #fff;
    line-height: 1.48;
  }
  .content p {
    font-size: 14px;
    line-height: 1.71;
    color: #fff;
  }
  .input-name-project {
    height: 50px;
  }
  .submit-form-button {
    width: 100%;
    height: 50px;
  }
  @media screen and (max-width: 600px) {
    .feedbo-main-logo {
      height: 42px;
      width: 42px;
    }
    .FeedboProject {
      font-size: 22px;
    }
    .form-container {
      width: 90%;
    }
    .content {
      padding-top: 15vh;
    }
  }
}
</style>

// new-apps/feedbo/src/pages/new-board/index.tsx
import { useState, useEffect } from 'react';
import { ArrowRight } from '@phosphor-icons/react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { __ } from '@wordpress/i18n';
import { AccountView } from '@/components/Account';
import { toast } from 'sonner';

export default function NewBoard() {
  const [user, setUser] = useState<any>(null);
  const [isAnonymous, setIsAnonymous] = useState(false);
  const [boardName, setBoardName] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    // Set document title
    if (window.feedbo?.siteName) {
      document.title = window.feedbo.siteName + ' | New Board';
    }

    // Set favicon
    const link = document.querySelector("link[rel*='icon']") as HTMLLinkElement || document.createElement('link');
    link.type = 'image/x-icon';
    link.rel = 'shortcut icon';
    link.href = window.feedbo?.pluginUrl + 'assets/img/feedbo-logo-square.png';
    if (!document.querySelector("link[rel*='icon']")) {
      document.getElementsByTagName('head')[0].appendChild(link);
    }

    // Fetch user data
    const fetchUser = async () => {
      try {
        // TODO: Replace with actual API call
        // const response = await fetch('/wp-json/feedbo/v1/user');
        // const userData = await response.json();

        // Mock user data for development
        const mockUser = {
          ID: 1,
          display_name: 'John Doe',
          user_email: 'john@example.com',
          user_avatar: window.feedbo?.pluginUrl + 'assets/img/default-avatar.png',
          list_board: [],
          notification: [
            {
              sendEmail: true,
              OwnPost: true,
              Comment: false
            }
          ]
        };

        setUser(mockUser);
        setIsAnonymous(false);
      } catch (error) {
        console.error('Failed to fetch user:', error);
        setIsAnonymous(true);
      }
    };

    fetchUser();
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Validate
    if (!boardName.trim()) {
      setError('This is a required field');
      return;
    }

    // Check if user is anonymous
    if (isAnonymous || !user) {
      window.location.href =
        window.feedbo?.siteUrl + '/wp-login.php?message=Please sign in to create your own board';
      return;
    }

    setIsLoading(true);
    setError('');

    try {
      // TODO: Replace with actual API call
      // const response = await fetch('/wp-json/feedbo/v1/boards', {
      //   method: 'POST',
      //   headers: { 'Content-Type': 'application/json' },
      //   body: JSON.stringify({ name: boardName })
      // });
      // const data = await response.json();

      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 2000));

      toast.success('Board created successfully!');
      
      // Redirect to the new board
      // window.location.href = `/#/board/${data.board_URL}`;
      
      // For now, redirect to home
      window.location.href = '/';
    } catch (error) {
      console.error('Failed to create board:', error);
      toast.error('Failed to create board. Please try again.');
      setIsLoading(false);
    }
  };

  const handleBoardChange = (boardUrl: string) => {
    window.location.href = `/#/board/${boardUrl}`;
  };

  const handleCreateBoard = () => {
    // Already on create board page
  };

  const handleAccountUpdate = (data: { name: string; email: string }) => {
    console.log('Update account:', data);
    // TODO: Add API call to update user account
  };

  const handleNotificationUpdate = (settings: any) => {
    console.log('Update notifications:', settings);
    // TODO: Add API call to update notification settings
  };

  const handleUnsubscribeAll = (userId: number) => {
    console.log('Unsubscribe user:', userId);
    // TODO: Add API call to unsubscribe from all posts
  };

  return (
    <div className="min-h-screen w-full bg-[#27ae60]">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-5">
        <div className="project-name">
          <a
            href="/"
            className="flex items-center text-2xl font-bold text-white no-underline md:text-2xl"
          >
            <img
              src={window.feedbo?.pluginUrl + 'assets/img/feedbo-logo-square.png'}
              alt="Feedbo Logo"
              className="h-[42px] w-[42px] md:h-[50px] md:w-[50px]"
            />
            <span className="pl-2.5">{__('Feedbo', 'feedbo')}</span>
          </a>
        </div>
        {user && (
          <AccountView
            user={user}
            isAnonymous={isAnonymous}
            onBoardChange={handleBoardChange}
            onCreateBoard={handleCreateBoard}
            onAccountUpdate={handleAccountUpdate}
            onNotificationUpdate={handleNotificationUpdate}
            onUnsubscribeAll={handleUnsubscribeAll}
          />
        )}
      </div>

      {/* Form Content */}
      <div className="mx-auto w-full max-w-[430px] px-4 pt-[15vh] md:pt-[30vh]">
        <div className="form-container">
          <h2 className="text-[21px] font-semibold leading-[1.48] text-white">
            {__('Create New Board', 'feedbo')}
          </h2>
          <p className="mb-6 text-sm leading-[1.71] text-white">
            {__('Enter your board name. You can change it later.', 'feedbo')}
          </p>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <Input
                type="text"
                placeholder={__('Enter name project', 'feedbo')}
                value={boardName}
                onChange={(e) => {
                  setBoardName(e.target.value);
                  if (error) setError('');
                }}
                className={`h-[50px] ${error ? 'border-red-500' : ''}`}
                disabled={isLoading}
              />
              {error && (
                <p className="mt-1 text-sm text-red-200">{error}</p>
              )}
            </div>

            <Button
              type="submit"
              className="h-[50px] w-full"
              disabled={isLoading}
            >
              {isLoading ? (
                __('Creating...', 'feedbo')
              ) : (
                <>
                  {__('Create', 'feedbo')}
                  <ArrowRight size={16} weight="bold" className="ml-2" />
                </>
              )}
            </Button>
          </form>
        </div>
      </div>
    </div>
  );
}
